[package]
name = "acctdiag"
version = "0.2.0"
authors = ["Andre Segura <andrensegura@gmail.com>"]

[dependencies]
lib_andre = { git = "https://github.com/andrensegura/lib_andre" , version = "0.1.1" }
walkdir = "0.1"
